# Generated by Django 5.0.4 on 2024-05-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0027_remove_transportrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Stage', 'Stage'), ('Logement', 'Logement'), ('Transport', 'Transport'), ('Recommandation', 'Recommandation')], max_length=50),
        ),
    ]
